### PR TITLE
Refactored code:

### PR DESCRIPTION
**Pull request by p5k369**
- compatible with python 3.10 and pyqt5
- complies with PEP 8

### CODE REVIEW

**Comment by p5k369** [comment]
Hey @fbjorn, we are using your waiting spinner in our project https://github.com/TUV-SUD-Product-Service-GmbH/QuteStyle.
However in general we prefer libraries that are closer to PEP 8 standards. Would you mind merging my PR or is that not a goal you are currently pursuing?

regards
Patrick

**Comment by fbjorn** [comment]
Hi @p5k369! Thanks for your interest in this project and for your effort and time to make this PR.
I will be honest, this codebase is in ugly shape. In the past I was developing PyQt application and I was in a hurry to add a spinner functionality. Then I quickly bootstrapped this repo without paying too much attention to the code quality. I don't remember all the details, but it was a port -- not my code, just some adaptation. 

But now I see people use it, so why not to improve it. I would say it like this - I will try to find some spare time in next couple of days to validate your PR and merge it, then maybe even set up CI/CD and add a better dependency manager. (Right now I can't even publish a new package with ease).

**Comment by p5k369** [comment]
In fact, that's also what we are doing and we also needed some feedback for the user that a thread is running atm. Initialy we used (what I think is the original python port from the C++ module) https://github.com/z3ntu/QtWaitingSpinner. 
But after some time we split our projects in smaller private and public repositories and also provide pypi packages for our public project via poetry. 
To keep dependencies simpler we chose to use your package from pypi.

Setting up poetry for your repository would be quite simple if you want to go the poetry path.
Also note, accepting the PR would led to major changes in the naming and behaviour of properties for example. They would look more pythonic but I totally understand if you want to be backwards compatible and don't want that to change.

**Comment by fbjorn** [comment]
@p5k369 FYI new version is available on PyPI: https://pypi.org/project/pyqtspinner/

**Pull request merged**
